# Enabling H2 Console
spring:
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        properties.hibernate.generate_statistics: true
        show-sql: true
        properties.hibernate.format_sql: true
    datasource:
        url: jdbc:h2:file:~/test
        username: sa
        password: null
        driver-class-name: org.h2.Driver

logging:
    level.org.hibernate.stat: debug
